
# hashing, signing, encrypt/decrypt, token utils

"""

class Crypto:
    def hash (self, value, algo='sha256'): ...
    def verify_hash (self, value, hashed): ...
    def encrypt (self, value, key): ...
    def decrypt (self, value, key): ...
    def random_token (self, length=32): ...
    
"""
